apiVersion: apps/v1
kind: Deployment
metadata:
  name: synergychat-web
  namespace: default
spec:
  selector:
    matchLabels:
      app: synergychat-web
  template:
    metadata:
      labels:
        app: synergychat-web
    spec:
      containers:
      - image: docker.io/bootdotdev/synergychat-web:latest
        imagePullPolicy: Always
        name: synergychat-web
        envFrom:
          - configMapRef:
              name: "web-service-configmap"
      